### PR TITLE
#288 Remove space between arg name and value, support of arg repeating with each value

### PR DESCRIPTION
**Pull request by miksir**
Issue #288

### CODE REVIEW

**Comment by bugy** [comment]
Or may be be same_arg_param

**Comment by miksir** [comment]
Renamed

**Comment by bugy** [comment]
There are 2 web tests failing, would you mind having a look? Or should I?

**Comment by miksir** [comment]
Oh, I will check.

**Comment by miksir** [comment]
Probably fired because I changed visibility of some fields when they are unused (they was disabled before)

**Pull request merged**
