### PR TITLE
Update deploy_docker.sh

### PR DESCRIPTION
**Pull request by bugy**

### CODE REVIEW

**Comment by bugy** [comment]
Test results: https://script-server-tests.s3-us-west-2.amazonaws.com/master/750/index.html

**Comment by vnghia** [comment]
The only thing we need to check is the docker build process, which is only triggered if we create a release :/

**Comment by vnghia** [comment]
Ah no, so the problem is deeper than I thought. Since the Docker image is just copying the process, which is specific for amd64. I will investigate and return back to you later

**Comment by bugy** [comment]
Sorry, which process are you talking about?

**Comment by vnghia** [comment]
> Sorry, which process are you talking about?

Sorry, I mean the output of the CI process, the `build/script-server.zip`

**Comment by bugy** [comment]
But the zip file should contain only python files, which are supposed to be platform independent

**Comment by vnghia** [comment]
I missed that part. Could you trigger the docker build ?

**Comment by bugy** [comment]
Test results: https://script-server-tests.s3-us-west-2.amazonaws.com/master/752/index.html

**Comment by bugy** [comment]
I'm trying to make docker image work for PRs

**Comment by bugy** [comment]
@vnghia there is an error:
```
unknown flag: --platform
```

**Comment by bugy** [comment]
https://app.travis-ci.com/github/bugy/script-server/builds/267081647

**Comment by vnghia** [comment]
Is there a way I can test it on my PR ?

**Comment by bugy** [comment]
can you try pushing any changes from your PR? I made a change to travis, probably it should build your PR now

**Comment by vnghia** [comment]
Still not running, but adding three lines here is good I think: https://github.com/bugy/script-server/pull/715/files#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485

**Comment by vnghia** [comment]
Can you show me the log :/

**Comment by bugy** [comment]
https://app.travis-ci.com/github/bugy/script-server/builds/267081647

don't you have access to this section?
image

**Comment by bugy** [comment]
btw, I gave you access to this repo, you can try doing changes in my branch

**Comment by vnghia** [comment]
I see the log now, Travis blocked me while I am on VPN :/

**Comment by vnghia** [comment]
hmm it seems that the CI won't run if there are my trace in the PR, maybe because I am a new contributor and it won't run unless you have to approve the PR once ?

**Review by vnghia — APPROVED** [review]

**Comment by bugy** [comment]
@vnghia I triggered the build manually and it worked! Could you try running it, please?
https://hub.docker.com/repository/docker/bugy/script-server/tags?page=1&ordering=last_updated

**Comment by vnghia** [comment]
It's working! Actually, you can test it on your own computer with `docker run --rm -it --platform linux/arm64 -p 5000:5000 bugy/script-server:test-amd-build` assuming that you have `qemu` installed.

**Comment by bugy** [comment]
Cool, thanks! Could you apply the same changes to your PR please? And then we merge it

**Comment by vnghia** [comment]
Done !

**Pull request closed without merging**
