### PR TITLE
Bug user_header_name

### PR DESCRIPTION
**Pull request by oktorok**
Modified `identification.py` and `audit_utils.py` as said in #292.

### CODE REVIEW

**Comment by bugy** [comment]
Oops, there are some tests failing now, could you have a look please?
https://travis-ci.org/github/bugy/script-server/builds/676418652

**Comment by oktorok** [comment]
I don't understand why they are failing, all the 23 errors are the same:
```
AttributeError: '' object has no attribute 'identification'
```
When calling `request_handler.application.identification.identify_for_audit(request_handler)` however if i execute the same tests they don't raise any error.
:(

**Comment by bugy** [comment]
Hi, I think the problem is in `ip_idenfication_test.py` line 15: request_handler mock doesn't specify `identification`, only `auth`

It might be the same for other tests

Regarding running tests locally: I couldn't reproduce it either. Most probably IP resolving works differently on travis and the tests goes into a bit different flow, where identification is required

**Comment by oktorok** [comment]
In `identification.py`, in `AuthBasedIdentification`
```
    def identify(self, request_handler):
        current_user = self._authentication_provider.get_username(request_handler)
        if not current_user:
            raise Exception('Not authenticated')
```
When `current_user` is `None` it raise an error, blocking some tests than before it returned none to `get_all_audit_names`, what whould be better? change the tests? or change identify? 

I think raise that error is important maybe change `identify_for_audit` for not call `identify`:
```
def identify_for_audit(self, request_handler):
        current_user = self._authentication_provider.get_username(request_handler)
        return current_user
```
What do you think?

**Comment by bugy** [comment]
Hi @oktorok, I see you already made some tries, thanks a lot for your effort and sorry for that!

Regarding the fix, I think changing the test would be better. I would prefer keeping production code behaviour and fail if something goes really wrong.

**Comment by oktorok** [comment]
Haha don't worry, i'm using this for learn OOP and actually is always have found debugging pretty fun.

Regarding the test, then now the correct behavior when identifying is raise Authentication error in some cases.
Then for change the tests, they should accept the error as the correct behavior? how do you specify to travis that an error is what he should expect?

**Comment by bugy** [comment]
There is a line above your changes
```
handler_mock.application.auth.get_username = lambda x: auth_username
```
As you can see, I'm not using real authenticator here, but just mock a simple one
The same you could do for your identification, instead of using real `AuthBasedIdentification`, you can define your custom identify method, e.g.
```
handler_mock.application.identification = mock_object()
handler_mock.application.identification.identify_for_audit = lambda x: auth_username
```
And actually I think you can safely remove everything related to `handler_mock.application.auth` in the `mock_request_handler` method

**Comment by oktorok** [comment]
Yeeeeeeyyy!!!

**Pull request merged**
